import "@/assets/styles/globals.scss";
import { ReactNode } from "react";
import ConfigureLinksStore from "@/store/links-store";

export const metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <ConfigureLinksStore />
      <body>{children}</body>
    </html>
  );
}
