import "@/assets/styles/globals.scss";
import { ReactNode } from "react";

export const metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
